export const EVENT_FORM_CONFIG = {
  Association: {
    pageTitle: "Create Association Event",
    pageDescription:
      "Create professional networking, conference, workshop, and association events.",
    defaultValues: {
      category: "professional",
      type: "on-campus",
      visibility: "public",
      registrationRequired: true,
      fee: "0",
      targetAudience: "all-students",
      tags: "professional, networking, development",
    },
    extraFields: [
      {
        name: "eventType",
        label: "Event Type",
        type: "select",
        required: true,
        options: [
          "Networking Session",
          "Professional Workshop",
          "Annual Conference",
          "Seminar/Talk",
          "Training Program",
          "Committee Meeting",
          "Social Gathering",
          "Award Ceremony",
          "Industry Visit",
          "Mentorship Program",
        ],
      },
      {
        name: "membershipRequired",
        label: "Membership Requirement",
        type: "select",
        options: [
          "open",
          "members",
          "members-guests",
          "invitation",
        ],
      },
      {
        name: "guestSpeakers",
        label: "Guest Speakers",
        type: "textarea",
      },
      {
        name: "professionalLevel",
        label: "Professional Level",
        type: "select",
        options: [
          "All Levels",
          "Students/Entry Level",
          "Junior Professionals",
          "Mid-Career Professionals",
          "Senior Executives",
          "Mixed Audience",
        ],
      },
      {
        name: "ceCredits",
        label: "Continuing Education Credits",
        type: "checkbox",
      },
      {
        name: "creditHours",
        label: "Credit Hours",
        type: "number",
        min: 0,
        step: 0.5,
      },
      {
        name: "industryFocus",
        label: "Industry Focus",
        type: "select",
        options: [
          "",
          "Technology",
          "Business",
          "Healthcare",
          "Education",
          "Engineering",
          "Arts & Media",
          "Science & Research",
          "Government",
          "Non-profit",
          "General",
        ],
      },
      {
        name: "networkingSession",
        label: "Includes Networking Session",
        type: "checkbox",
      },
      {
        name: "certificationProvided",
        label: "Certification Provided",
        type: "checkbox",
      },
    ],
  },

  Club: {
    pageTitle: "Create Club Event",
    pageDescription:
      "Create club competitions, workshops, meetups, and member engagement events.",
    defaultValues: {
      category: "competition",
      type: "on-campus",
      visibility: "public",
      registrationRequired: true,
      fee: "0",
      targetAudience: "all-students",
      tags: "club, student, activity",
    },
    extraFields: [
      {
        name: "eventFormat",
        label: "Event Format",
        type: "select",
        required: true,
        options: [
          "Competition",
          "Workshop",
          "Seminar",
          "Meetup",
          "Showcase",
          "Training Session",
          "Tournament",
        ],
      },
      {
        name: "teamSize",
        label: "Team Size",
        type: "number",
        min: 1,
      },
      {
        name: "skillLevel",
        label: "Skill Level",
        type: "select",
        options: ["Beginner", "Intermediate", "Advanced", "Open"],
      },
      {
        name: "judgingCriteria",
        label: "Judging Criteria",
        type: "textarea",
      },
      {
        name: "prizeDetails",
        label: "Prize Details",
        type: "textarea",
      },
      {
        name: "materialsRequired",
        label: "Materials Required",
        type: "textarea",
      },
    ],
  },

  "Social Service": {
    pageTitle: "Create Social Service Event",
    pageDescription:
      "Create blood donation, relief, awareness, and community service events.",
    defaultValues: {
      category: "charity",
      type: "on-campus",
      visibility: "public",
      registrationRequired: true,
      fee: "0",
      targetAudience: "all-students",
      tags: "service, volunteering, social-impact",
    },
    extraFields: [
      {
        name: "serviceType",
        label: "Service Type",
        type: "select",
        required: true,
        options: [
          "Blood Donation",
          "Health Camp",
          "Relief Distribution",
          "Awareness Campaign",
          "Volunteer Drive",
          "Fundraising",
        ],
      },
      {
        name: "medicalRequirements",
        label: "Medical Requirements",
        type: "textarea",
      },
      {
        name: "volunteerCount",
        label: "Volunteer Count",
        type: "number",
        min: 0,
      },
      {
        name: "eligibilityCriteria",
        label: "Eligibility Criteria",
        type: "textarea",
      },
      {
        name: "equipmentProvided",
        label: "Equipment Provided",
        type: "textarea",
      },
      {
        name: "postEventSupport",
        label: "Post Event Support",
        type: "checkbox",
      },
    ],
  },
};

export const COMMON_EVENT_DEFAULTS = {
  title: "",
  shortDesc: "",
  longDesc: "",
  organization: "",
  organizationEmail: "",
  type: "on-campus",
  category: "",
  location: "",
  startAt: "",
  endAt: "",
  registrationDeadline: "",
  registrationRequired: true,
  maxCapacity: "",
  pricingType: "free",
  fee: "0",
  paymentDeadline: "",
  refundPolicy: "No refunds after confirmation.",
  paymentInstructions: "",
  scholarshipSeats: "",
  contactName: "",
  contactEmail: "",
  contactPhone: "",
  tags: "",
  visibility: "public",
  cover: null,
  requirements: "",
  targetAudience: "all-students",
};