import { useMemo } from "react";
import { useQuery } from "@tanstack/react-query";
import {
    CreditCard,
    Receipt,
    Wallet,
    CalendarCheck2,
    FileDown,
    Printer,
} from "lucide-react";
import useUserRole from "../../../hooks/useUserRole";
import API from "../../../utils/api";
import useInfiniteScrollSlice from "../../../hooks/useInfiniteScrollSlice";

const OrganizationPayments = () => {
    const { userInfo } = useUserRole();
    const {
        data: payments = [],
        isLoading: loading,
    } = useQuery({
        queryKey: ["organization-payments", userInfo?.email],
        enabled: Boolean(userInfo?.email),
        queryFn: async () => {
            const response = await API.get(
                `/payments/organization/${encodeURIComponent(userInfo.email)}`
            );
            return Array.isArray(response?.data) ? response.data : [];
        },
        staleTime: 1000 * 60 * 5,
        gcTime: 1000 * 60 * 20,
        refetchOnWindowFocus: false,
    });

    const {
        visibleItems: visiblePayments,
        hasMore: hasMorePayments,
        loadMoreRef: paymentsLoadMoreRef,
    } = useInfiniteScrollSlice(payments, {
        pageSize: 20,
        resetDeps: [payments.length],
    });

    const summary = useMemo(() => {
        const totalRevenue = payments.reduce((sum, item) => sum + Number(item.amount || 0), 0);
        const uniqueEvents = new Set(payments.map((item) => item.eventId)).size;
        const thisMonth = new Date().getMonth();
        const monthlyRevenue = payments
            .filter((item) => new Date(item.paidAt).getMonth() === thisMonth)
            .reduce((sum, item) => sum + Number(item.amount || 0), 0);

        return {
            totalRevenue,
            totalTransactions: payments.length,
            uniqueEvents,
            monthlyRevenue,
        };
    }, [payments]);

        const downloadReceiptPdfStyle = (payment) => {
                const receiptHtml = `
<!doctype html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>Payment Receipt - ${payment.transactionId}</title>
        <style>
            body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #f8fafc; margin: 0; padding: 24px; }
            .card { max-width: 760px; margin: 0 auto; background: #fff; border: 1px solid #e2e8f0; border-radius: 16px; overflow: hidden; }
            .header { padding: 24px; background: linear-gradient(135deg, #0f172a, #334155); color: #fff; }
            .header h1 { margin: 0; font-size: 24px; }
            .header p { margin-top: 8px; opacity: .85; }
            .body { padding: 24px; }
            .row { display: flex; justify-content: space-between; gap: 16px; padding: 10px 0; border-bottom: 1px dashed #e2e8f0; }
            .row:last-child { border-bottom: none; }
            .label { color: #64748b; }
            .value { color: #0f172a; font-weight: 600; text-align: right; }
            .footer { padding: 20px 24px; border-top: 1px solid #e2e8f0; font-size: 12px; color: #64748b; }
            @media print {
                body { background: #fff; padding: 0; }
                .card { border: none; border-radius: 0; }
            }
        </style>
    </head>
    <body>
        <div class="card">
            <div class="header">
                <h1>Payment Receipt</h1>
                <p>Transaction confirmed and recorded for internal reconciliation.</p>
            </div>
            <div class="body">
                <div class="row"><span class="label">Transaction ID</span><span class="value">${payment.transactionId}</span></div>
                <div class="row"><span class="label">Event</span><span class="value">${payment.eventTitle}</span></div>
                <div class="row"><span class="label">Payer</span><span class="value">${payment.studentName || payment.studentEmail}</span></div>
                <div class="row"><span class="label">Amount</span><span class="value">BDT ${Number(payment.amount || 0).toLocaleString()}</span></div>
                <div class="row"><span class="label">Method</span><span class="value">${payment.method || "card"}</span></div>
                <div class="row"><span class="label">Status</span><span class="value">${payment.status}</span></div>
                <div class="row"><span class="label">Paid At</span><span class="value">${new Date(payment.paidAt).toLocaleString()}</span></div>
            </div>
            <div class="footer">
                Generated by Aidevo Payments. Use browser "Save as PDF" in print dialog for file download.
            </div>
        </div>
        <script>window.onload = () => window.print();</script>
    </body>
</html>`;

                const printWindow = window.open("", "_blank", "width=900,height=760");
                if (!printWindow) return;
                printWindow.document.open();
                printWindow.document.write(receiptHtml);
                printWindow.document.close();
        };

        const exportPayoutSummaryCsv = () => {
                if (!payments.length) return;

                const byEvent = payments.reduce((acc, item) => {
                        const key = String(item.eventId || "unknown");
                        if (!acc[key]) {
                                acc[key] = {
                                        eventId: item.eventId || "",
                                        eventTitle: item.eventTitle || "",
                                        totalRevenue: 0,
                                        transactions: 0,
                                };
                        }

                        acc[key].totalRevenue += Number(item.amount || 0);
                        acc[key].transactions += 1;
                        return acc;
                }, {});

                const rows = Object.values(byEvent);
                const header = ["Event ID", "Event Title", "Transactions", "Total Revenue (BDT)"];
                const csvBody = rows.map((row) => [
                        row.eventId,
                        `"${String(row.eventTitle).replace(/"/g, '""')}"`,
                        row.transactions,
                        row.totalRevenue,
                ].join(","));

                const csvContent = [header.join(","), ...csvBody].join("\n");
                const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
                const url = URL.createObjectURL(blob);
                const link = document.createElement("a");
                link.href = url;
                link.download = `payout-summary-${new Date().toISOString().slice(0, 10)}.csv`;
                document.body.appendChild(link);
                link.click();
                document.body.removeChild(link);
                URL.revokeObjectURL(url);
        };

    if (loading) {
        return (
            <div className="space-y-6">
                <div className="app-surface p-6 animate-pulse">
                    <div className="h-8 w-44 rounded bg-gray-200 mb-3" />
                    <div className="h-4 w-80 rounded bg-gray-200" />
                </div>
                <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-4">
                    {[1, 2, 3, 4].map((item) => (
                        <div key={item} className="app-surface p-5 animate-pulse">
                            <div className="h-4 w-24 rounded bg-gray-200 mb-4" />
                            <div className="h-8 w-24 rounded bg-gray-200" />
                        </div>
                    ))}
                </div>
                <div className="app-surface p-5 animate-pulse min-h-[280px]">
                    <div className="h-6 w-56 rounded bg-gray-200 mb-4" />
                    <div className="space-y-3">
                        {[1, 2, 3, 4].map((row) => (
                            <div key={row} className="h-12 rounded bg-gray-200" />
                        ))}
                    </div>
                </div>
            </div>
        );
    }

    return (
        <div className="space-y-6">
            <div className="app-surface p-6">
                <div className="flex justify-end">
                    <button
                        onClick={exportPayoutSummaryCsv}
                        disabled={!payments.length}
                        className="app-btn-secondary"
                    >
                        <FileDown className="w-4 h-4" />
                        Export Payout CSV
                    </button>
                </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-4">
                <div className="app-surface p-5">
                    <div className="flex items-center justify-between mb-2">
                        <p className="text-sm text-slate-600">Total Revenue</p>
                        <Wallet className="w-5 h-5 text-emerald-600" />
                    </div>
                    <p className="text-2xl font-bold text-slate-900">BDT {summary.totalRevenue.toLocaleString()}</p>
                </div>
                <div className="app-surface p-5">
                    <div className="flex items-center justify-between mb-2">
                        <p className="text-sm text-slate-600">Transactions</p>
                        <Receipt className="w-5 h-5 text-sky-600" />
                    </div>
                    <p className="text-2xl font-bold text-slate-900">{summary.totalTransactions}</p>
                </div>
                <div className="app-surface p-5">
                    <div className="flex items-center justify-between mb-2">
                        <p className="text-sm text-slate-600">Paid Events</p>
                        <CalendarCheck2 className="w-5 h-5 text-violet-600" />
                    </div>
                    <p className="text-2xl font-bold text-slate-900">{summary.uniqueEvents}</p>
                </div>
                <div className="app-surface p-5">
                    <div className="flex items-center justify-between mb-2">
                        <p className="text-sm text-slate-600">This Month</p>
                        <CreditCard className="w-5 h-5 text-amber-600" />
                    </div>
                    <p className="text-2xl font-bold text-slate-900">BDT {summary.monthlyRevenue.toLocaleString()}</p>
                </div>
            </div>

            <div className="app-surface overflow-hidden">
                <div className="px-5 py-4 border-b border-slate-100">
                    <h2 className="text-lg font-semibold text-slate-900">Recent Transactions</h2>
                </div>

                {payments.length === 0 ? (
                    <p className="p-6 text-sm text-slate-500">No payments found yet.</p>
                ) : (
                    <div className="overflow-x-auto">
                        <table className="w-full text-sm">
                            <thead className="bg-slate-50">
                                <tr className="text-left text-slate-600">
                                    <th className="px-5 py-3 font-medium">Event</th>
                                    <th className="px-5 py-3 font-medium">Student</th>
                                    <th className="px-5 py-3 font-medium">Amount</th>
                                    <th className="px-5 py-3 font-medium">Transaction ID</th>
                                    <th className="px-5 py-3 font-medium">Status</th>
                                    <th className="px-5 py-3 font-medium">Receipt</th>
                                </tr>
                            </thead>
                            <tbody>
                                {visiblePayments.map((payment) => (
                                    <tr key={String(payment._id)} className="border-t border-slate-100">
                                        <td className="px-5 py-3 text-slate-900 font-medium">{payment.eventTitle}</td>
                                        <td className="px-5 py-3 text-slate-700">{payment.studentName || payment.studentEmail}</td>
                                        <td className="px-5 py-3 text-slate-900">BDT {Number(payment.amount || 0).toLocaleString()}</td>
                                        <td className="px-5 py-3 text-slate-600">{payment.transactionId}</td>
                                        <td className="px-5 py-3">
                                            <span className="inline-flex px-2 py-1 rounded-full bg-emerald-100 text-emerald-700 text-xs font-semibold">
                                                {payment.status}
                                            </span>
                                        </td>
                                        <td className="px-5 py-3">
                                            <button
                                                onClick={() => downloadReceiptPdfStyle(payment)}
                                                className="app-btn-secondary !px-2.5 !py-1.5"
                                            >
                                                <Printer className="w-3.5 h-3.5" />
                                                PDF-style
                                            </button>
                                        </td>
                                    </tr>
                                ))}
                                {hasMorePayments && (
                                    <tr>
                                        <td colSpan={6} className="px-5 py-4 text-center text-xs text-slate-500">
                                            <div ref={paymentsLoadMoreRef}>Loading more transactions...</div>
                                        </td>
                                    </tr>
                                )}
                            </tbody>
                        </table>
                    </div>
                )}
            </div>
        </div>
    );
};

export default OrganizationPayments;